[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer_runs = 200
rpc_endpoints = { holesky = "https://ethereum-holesky.publicnode.com" }
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
